baseURL = "https://danielorihuela.github.io/"
languageCode = "en-us"
title = "danielorihuela"
theme = "do-cyberpunk-theme"

[markup]
  [markup.highlight]
    noClasses = false

[menu]
[[menu.main]]
  identifier = 'about'
  title = 'About'
  url = 'about'
  weight = 1
  [menu.main.params]
    icon = 'about.svg'
    borderRadius = '50%'
[[menu.main]]
  identifier = 'posts'
  title = 'Posts'
  url = 'posts'
  weight = 2
  [menu.main.params]
    icon = 'file-manager.svg'
[[menu.main]]
  identifier = 'open-source'
  title = 'OSS Contributions'
  url = 'open-source'
  weight = 3
  [menu.main.params]
    icon = 'open-source.png'

[Params]
  github = 'https://github.com/danielorihuela'
  email = 'danielorihuelarodriguez@gmail.com'
  twitter = 'https://twitter.com/_DanielOrihuela'