baseURL = "https://danielorihuela.github.io/"
languageCode = "en-us"
title = "danielorihuela"
theme = "do-cyberpunk-theme"

[menu]
[[menu.main]]
  identifier = 'about'
  title = 'about'
  url = 'about'
  [menu.main.params]
    icon = 'about.jpg'
    borderRadius = '50%'
[[menu.main]]
  identifier = 'posts'
  title = 'posts'
  url = 'posts'
  [menu.main.params]
    icon = 'file-manager.svg'

[Params]
  github = 'https://github.com/danielorihuela'
  email = 'danielorihuelarodriguez@gmail.com'