name: deploy site

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command npm run build
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/development' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./dist